server:
  port: 5000

#spring:
#  datasource:
#    url: jdbc:h2:file:~/testdb
#    driver-class-name: org.h2.Driver
#    username: sa
#    password:
#
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    properties:
#       hibernate:
#         format_sql: true
#         use_sql_comments: true
#
#  h2:
#    console:
#      enabled: true
#      path: /h2-console

spring:
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    datasource:
      url: jdbc:mysql://awseb-e-zmcppsmiid-stack-awsebrdsdatabase-35exkg2tm0ob.cdkacaomigq5.ap-northeast-2.rds.amazonaws.com:3306/ebdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      username: tripmate
      password: patty2331

file:
  upload-dir: ./uploads

jwt:
  secret-key: MjU2Yml0c2VjcmV0a2V5Zm9yand0YXV0aGVuY2F0aW9uMjU2Yml0c2VjcmV0a2V5Zm9yand0YXV0aGVuY2F0aW9u
